
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: JADE
subtitle: "Joint Academic Data science Endeavour (JADE) System"
# Base URL of site. It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
# baseurl: "/" # the subpath of your site

url: "//jade-hpc-gpu.github.io"
baseurl: ""
paginate_path: "/blog/page:num/"
logo: "/img/logo/JADE__2.5_Logo.svg"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: /:year-:month-:day-:title/
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

gems:
  - jekyll-paginate

# Google analytics
google_analytics: UA-... #Mozhgan change 

